numero= input()
# no iniciar con numero, no espacios , no caracteres especiales
print(numero)
numero= input("Sr usuario digite un numero")
print("el numero que digito, mas 2 fue : " , int(numero) +2)
int("123")
var= input('sr usuario,  digite numero :')
print('usted acaba de digitar lo siguiente  :', var)
print(int(var)+2)
var= float(var)
print(var+2)
numero= int(input( 'sr usuario, digite numero'))
print(f'el numero que digito fue :{numero}')
number= bool(input( 'digite numero: '))
print(f'la variable "number" es igual a  :{number}')